services:
  - type: web
    name: seo-insight
    env: docker
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: TZ
        value: Asia/Kolkata
      - key: DATABASE_URL
        value: sqlite:////var/data/seo_insight.db
      - key: PAGESPEED_API_KEY
        sync: false
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: FROM_EMAIL
        sync: false
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
